spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/soft?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 123456
  mail:
    host: smtp.163.com
    username: zhangshuui@163.com
    password: BJAXTSPNXUVIUXFS
    port: 465
    properties:
      from: zhangshuui@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379